### ISSUE TITLE
Issue: OVERWRITE existing state-file

### ISSUE THREAD

**Issue by karthikholla** [aramalipoor/aws-cost-saver#29]
When using **--state-file s3://** on a daily scheduled cron., the job fails for the second time and further with error
 
`→ State file already exists: s3://***/staging-state-file.json
? Are you sure you want to OVERWRITE existing state-file?
  You will not be able to restore to previously conserved resources! (y/N) `

Please enable overwrite flag while using --state-file s3://

**Comment by aramalipoor** [comment]
Hi Karthik, thanks for trying out aws-cost-saver :)

Do you think using [this approach](https://github.com/aramalipoor/aws-cost-saver#keeping-an-ideal-state-file) of snapshotting an ideal state-file once and passing `-n` (i.e. `--no-state-file`) for the scheduled cron will work for your use-case?

If not, I'm happy to add an optional flag like `--overwrite-state-file` for you to try it out. 

As you know I added this check to avoid overwriting a state-file that's not yet restored, maybe in case of dev/stage that's too strict 🤔

**Comment by aramalipoor** [comment]
Released `-w|--overwrite-state-file` in [v0.1.0](https://www.npmjs.com/package/aws-cost-saver), let me know if it helps with your use-case.

**Comment by karthikholla** [comment]
Thanks @aramalipoor `-n` option wont work for me as we may have a couple of teams working on each environment and there is no ideal state file we can maintain. Each day the AWS resources get provisioned and de-provisioned as & when its required. Hence at the end of each day, we need to run this library to conserve all the running and restore it next day exactly. 

yes. this rewrite functionality will definitely help us with that. Thanks for it. will try it out.
