### ISSUE TITLE
feature: Allow filtering by tag

### ISSUE THREAD

**Issue by aramalipoor** [aramalipoor/aws-cost-saver#6]
Discussed by [rxDotIo and twratl on reddit](https://www.reddit.com/r/aws/comments/iell1j/tiny_cli_to_save_aws_costs_in_development/g2hvpx4/?utm_source=reddit&utm_medium=web2x&context=3).

**Comment by rpidanny** [comment]
How about a new flag `--filter-with-tag` ? or simply just `--tag`?

**Comment by 037g** [comment]
This would be a killer feature!

**Comment by aramalipoor** [comment]
@037g @rpidanny just released [v0.2.1](https://www.npmjs.com/package/aws-cost-saver) with a new `-t | --tag` flag. Give it a try and let me know if it works for you :)

**Comment by rpidanny** [comment]
> @037g @rpidanny just released [v0.2.1](https://www.npmjs.com/package/aws-cost-saver) with a new `-t | --tag` flag. Give it a try and let me know if it works for you :)

Awesome @aramalipoor 🥳 I will try it out 😄
